import React from 'react'

function About() {
  return (
    <div>
      <h1>About</h1>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos reiciendis voluptate aut in dicta quidem sequi harum laudantium necessitatibus enim molestiae maxime, deserunt dolore iste fugiat culpa sint cum numquam temporibus ad eum laborum. Natus incidunt libero cumque reiciendis, deleniti eius numquam sequi doloribus dicta quas ducimus modi officiis consequuntur obcaecati minima. Blanditiis est quia, cum nulla molestiae laborum quaerat sit vero natus voluptate corrupti ipsa tempore id aperiam fugiat saepe aspernatur perspiciatis, ea animi debitis dolorem, dicta quis. Ipsum, placeat. Molestiae, veniam fugiat? Veniam illum quas soluta, non accusantium voluptas, nihil aliquid consectetur facilis commodi id explicabo neque excepturi numquam perferendis qui ad dignissimos fuga nemo labore magnam ipsum. Minus dignissimos eos maiores aut quidem veritatis in id totam. Officiis itaque numquam animi! Veniam minus aliquid, quas tenetur nulla molestias illum dolor ut fuga fugiat eos laborum temporibus, earum voluptatum sequi ab esse illo excepturi libero suscipit eius. Ullam quo, laudantium natus, amet et nam praesentium quod esse ducimus magni omnis beatae ut cum dolorum deserunt iure perferendis expedita officia labore saepe aut corrupti obcaecati maxime fugit? Similique dolorum consectetur ipsam repellat, hic minus itaque quibusdam dicta voluptatum repellendus modi eaque iste perferendis iusto sequi mollitia consequatur quasi recusandae?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos reiciendis voluptate aut in dicta quidem sequi harum laudantium necessitatibus enim molestiae maxime, deserunt dolore iste fugiat culpa sint cum numquam temporibus ad eum laborum. Natus incidunt libero cumque reiciendis, deleniti eius numquam sequi doloribus dicta quas ducimus modi officiis consequuntur obcaecati minima. Blanditiis est quia, cum nulla molestiae laborum quaerat sit vero natus voluptate corrupti ipsa tempore id aperiam fugiat saepe aspernatur perspiciatis, ea animi debitis dolorem, dicta quis. Ipsum, placeat. Molestiae, veniam fugiat? Veniam illum quas soluta, non accusantium voluptas, nihil aliquid consectetur facilis commodi id explicabo neque excepturi numquam perferendis qui ad dignissimos fuga nemo labore magnam ipsum. Minus dignissimos eos maiores aut quidem veritatis in id totam. Officiis itaque numquam animi! Veniam minus aliquid, quas tenetur nulla molestias illum dolor ut fuga fugiat eos laborum temporibus, earum voluptatum sequi ab esse illo excepturi libero suscipit eius. Ullam quo, laudantium natus, amet et nam praesentium quod esse ducimus magni omnis beatae ut cum dolorum deserunt iure perferendis expedita officia labore saepe aut corrupti obcaecati maxime fugit? Similique dolorum consectetur ipsam repellat, hic minus itaque quibusdam dicta voluptatum repellendus modi eaque iste perferendis iusto sequi mollitia consequatur quasi recusandae?</p>
   
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos reiciendis voluptate aut in dicta quidem sequi harum laudantium necessitatibus enim molestiae maxime, deserunt dolore iste fugiat culpa sint cum numquam temporibus ad eum laborum. Natus incidunt libero cumque reiciendis, deleniti eius numquam sequi doloribus dicta quas ducimus modi officiis consequuntur obcaecati minima. Blanditiis est quia, cum nulla molestiae laborum quaerat sit vero natus voluptate corrupti ipsa tempore id aperiam fugiat saepe aspernatur perspiciatis, ea animi debitis dolorem, dicta quis. Ipsum, placeat. Molestiae, veniam fugiat? Veniam illum quas soluta, non accusantium voluptas, nihil aliquid consectetur facilis commodi id explicabo neque excepturi numquam perferendis qui ad dignissimos fuga nemo labore magnam ipsum. Minus dignissimos eos maiores aut quidem veritatis in id totam. Officiis itaque numquam animi! Veniam minus aliquid, quas tenetur nulla molestias illum dolor ut fuga fugiat eos laborum temporibus, earum voluptatum sequi ab esse illo excepturi libero suscipit eius. Ullam quo, laudantium natus, amet et nam praesentium quod esse ducimus magni omnis beatae ut cum dolorum deserunt iure perferendis expedita officia labore saepe aut corrupti obcaecati maxime fugit? Similique dolorum consectetur ipsam repellat, hic minus itaque quibusdam dicta voluptatum repellendus modi eaque iste perferendis iusto sequi mollitia consequatur quasi recusandae?</p>
   
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos reiciendis voluptate aut in dicta quidem sequi harum laudantium necessitatibus enim molestiae maxime, deserunt dolore iste fugiat culpa sint cum numquam temporibus ad eum laborum. Natus incidunt libero cumque reiciendis, deleniti eius numquam sequi doloribus dicta quas ducimus modi officiis consequuntur obcaecati minima. Blanditiis est quia, cum nulla molestiae laborum quaerat sit vero natus voluptate corrupti ipsa tempore id aperiam fugiat saepe aspernatur perspiciatis, ea animi debitis dolorem, dicta quis. Ipsum, placeat. Molestiae, veniam fugiat? Veniam illum quas soluta, non accusantium voluptas, nihil aliquid consectetur facilis commodi id explicabo neque excepturi numquam perferendis qui ad dignissimos fuga nemo labore magnam ipsum. Minus dignissimos eos maiores aut quidem veritatis in id totam. Officiis itaque numquam animi! Veniam minus aliquid, quas tenetur nulla molestias illum dolor ut fuga fugiat eos laborum temporibus, earum voluptatum sequi ab esse illo excepturi libero suscipit eius. Ullam quo, laudantium natus, amet et nam praesentium quod esse ducimus magni omnis beatae ut cum dolorum deserunt iure perferendis expedita officia labore saepe aut corrupti obcaecati maxime fugit? Similique dolorum consectetur ipsam repellat, hic minus itaque quibusdam dicta voluptatum repellendus modi eaque iste perferendis iusto sequi mollitia consequatur quasi recusandae?</p>
   
    </div>
  )
}

export default About
